name: Flutter Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
      - run: flutter pub get
      - run: flutter test
      - run: flutter analyze lib/templates/lab8/
      - run: flutter build web --target=lib/templates/lab8/main.dart
      - name: pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
